accounts/urls.py
from django.urls import path
from accounts.views import login_page, signup_page, logout_page, profile, user_update, delete_account

app_name = 'accounts'

urlpatterns = [
    path('login/', login_page, name='login'),
    path('signup/', signup_page, name='signup'),
    path('logout/', logout_page, name='logout'),
    path("profile/", profile, name='profile'),
    path("update/", user_update, name='update_profile'),
    path("delete/", delete_account, name='delete_account'),
]

vacansies_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(f'admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('users/', include('accounts.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class CustomUserManager(BaseUserManager):
    
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """Модель кастомного пользователя"""

    email = models.EmailField(
        "email пользователя",
        max_length=260,
        unique=True
    )
    city = models.ForeignKey(
        'main_app.Cities',
        related_name='city_users',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Ваш город'
    )
    language = models.ForeignKey(
        'main_app.ProgramLanguage',
        related_name='lang_users',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Ваш язык программирования'
    )
    subscribed = models.BooleanField("Подписка на рассылку", default=False)
    is_active = models.BooleanField("Активный аккаунт", default=False)
    is_superuser = models.BooleanField("Статус суперпользователя", default=False)
    is_staff = models.BooleanField("Статус персонала", default=False)
    date_joined = models.DateTimeField("Дата регистрации", auto_now_add=True)
    objects = CustomUserManager()
    USERNAME_FIELD = 'email'
    
    def __str__(self):
        return f'{self.email}'
    
    class Meta:
        verbose_name = 'Пользователи'
        verbose_name_plural = 'Список пользателей'

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from accounts.models import CustomUser
from main_app.models import Cities, ProgramLanguage

User = get_user_model()


class LoginForm(forms.Form):
    """Форма для входа"""

    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={'placeholder': "email", "class": 'form-control'})
    )
    password = forms.CharField(
        max_length=150,
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': "Пароль*", "class": 'form-control'})
    )


class SignUpForm(UserCreationForm):
    """Форма для регистрации"""

    password1 = forms.CharField(
        label='',
        max_length=300,
        widget=forms.PasswordInput(attrs={'placeholder': "Пароль"})
    )
    password2 = forms.CharField(
        label='',
        max_length=300,
        widget=forms.PasswordInput(attrs={'placeholder': "Пароль ещё раз"})
    )

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': "Email*"})
        }


class UserUpdateForm(forms.ModelForm):
    """Форма для обновления профиля юзера"""

    city = forms.ModelChoiceField(
        queryset=Cities.objects.all(),
        to_field_name="slug",
        required=False,
        label='Город'
    )
    language = forms.ModelChoiceField(
        queryset=ProgramLanguage.objects.all(),
        to_field_name="slug",
        required=False,
        label='Язык программирования'
    )
    subscribed = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput,
        label='Подписка на рассылку'                              
    )
    password1 = forms.CharField(
        label='',
        max_length=300,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        required=False
    )
    password2 = forms.CharField(
        label='',
        max_length=300,
        widget=forms.PasswordInput(attrs={"autocomplete": "false"}),
        required=False
    )

    class Meta:
        model = User
        fields = ('city', 'language', 'subscribed', 'password1', 'password2')


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email', )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login, get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from accounts.forms import LoginForm, SignUpForm, UserUpdateForm
from accounts.tasks import hello_sender

User = get_user_model()


def login_page(request):
    """Страница для логина"""

    if request.user.is_authenticated:
        return redirect('main_app:home')
    if request.user.is_anonymous and request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_data = login_form.cleaned_data
            email = user_data['email']
            password = user_data['password']
            check_email = User.objects.filter(email=email).first()
            if check_email:
                auth_user = authenticate(request, email=email, password=password)
                if auth_user:
                    login(request, auth_user)
                    messages.success(request, 'Вы успешно вошли в систему!')
                    return redirect('main_app:home')
                else:
                    messages.error(request, 'Логин или пароль неправильные')
            else:
                messages.error(request, 'Пользователь с таким email не существует!')
    else:
        login_form = LoginForm()
    context = {
        'title': "Вход",
        'login_form': login_form,
    }
    return render(
        request,
        'accounts/login_page.html',
        context=context
    )


def signup_page(request):
    """Страница для регистрации"""

    if request.user.is_authenticated:
        return redirect('main_app:home')
    if request.user.is_anonymous and request.method == "POST":
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user_data = signup_form.cleaned_data
            email = user_data['email']
            check_email = User.objects.filter(email=email).first()
            if not check_email:
                password = user_data['password1']
                user = signup_form.save(commit=False)
                user.is_active = True
                user.set_password(password)
                user.save()
                hello_sender.delay(email)
                messages.success(request, 'Вы успешно зарегистрировались! Теперь войдите в систему')
                return redirect('accounts:login')
            else:
                messages.error(request, 'Пользователь с таким email уже существует!')
    else:
        signup_form = SignUpForm()
    context = {
        'title': "Регистрация",
        'signup_form': signup_form,
    }
    return render(
        request,
        'accounts/signup_page.html',
        context=context
    )


@login_required(login_url='accounts:login')
def logout_page(request):
    """Страница для выхода"""

    if request.method == "GET":
        logout(request)
        messages.success(request, 'Вы успешно вышли')
    else:
        messages.info(request, 'Метод POST не разрешен')
    return redirect('main_app:home')


@login_required(login_url='accounts:login')
def profile(request):
    """Страница для просмотра профиля"""

    context = {
        'title': "Мой профиль",
    }
    return render(
        request,
        'accounts/profile.html',
        context=context
    )


@login_required(login_url='accounts:login')
def user_update(request):
    """Страница для обновления профиля"""

    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            valid_data = form.cleaned_data
            if valid_data['password1'] != valid_data['password2']:
                messages.error(request, 'Пароли не совпадают!')
                return redirect("accounts:update_profile")
            user = form.save(commit=False)
            new_password = valid_data['password1']
            if len(new_password) > 0:
                if len(new_password) < 8:
                    messages.error(request, 'Пароль не должен быть менее 8 символов!')
                    return redirect("accounts:update_profile")
                user.set_password(new_password)
            user.save()
            messages.success(request, 'Данные успешно изменены')
            update_session_auth_hash(request, user)
            return redirect("accounts:profile")
    else:
        initial_data = {
            "city": request.user.city,
            "language": request.user.language,
            'subscribed': request.user.subscribed
        }
        form = UserUpdateForm(initial=initial_data)
    context = {
        "form": form,
        "title": "Обновление профиля"
    }
    return render(
        request,
        'accounts/update_page.html',
        context=context
    )


@login_required(login_url='accounts:login')
def delete_account(request):
    if request.method != "POST":
        messages.info(request, 'Разрешен только POST запрос!')
        return redirect('accounts:profile')
    user = User.objects.get(pk=request.user.pk)
    user.delete()
    messages.success(request, 'Ваш аккаунт успешно удален!')
    return redirect('main_app:home')

accounts/templates/accounts/include/forms/login.html
<div class="login-form container-fluid d-flex h-100 justify-content-center align-items-center p-0">
	<div class="row bg-white shadow-sm">
		<div class="col border rounded p-4">
			<h3 class="text-center mb-4" style="color: black;">Вход</h3>
			<form action="{% url 'accounts:login' %}" method="post">
				{% csrf_token %}
				{% if login_form.email.errors %}
					<ol style="color: red;">
					{% for error in login_form.email.errors %}
						<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
					{% endfor %}
					</ol>
				{% endif %}
				{% if login_form.password.errors %}
					<ol style="color: red;">
					{% for error in login_form.password.errors %}
						<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
					{% endfor %}
					</ol>
				{% endif %}
				<div class="form-group" style="text-align: center;">
					{{ login_form.email }}
					<br>
					{{ login_form.password }}
				</div>
				<br>
				<button type="submit" class="btn btn-danger">Войти</button>
				<br><br>
				<div>
					<p>Нет аккаунта? <a href="{% url 'accounts:signup' %}" class="text text-danger" style="color: black;">Зарегистрироваться</a></p>
				</div>
			</form>
		</div>
	</div>
</div>

accounts/templates/accounts/include/forms/signup.html
<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Регистрация</p>
<form class="mx-1 mx-md-4" action="{% url 'accounts:signup' %}" method="post">
	{% csrf_token %}
	{% if signup_form.email.errors %}
		<ol style="color: red;">
			{% for error in signup_form.email.errors %}
				<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
			{% endfor %}
		</ol>
	{% endif %}
	{% if signup_form.password1.errors %}
		<ol style="color: red;">
			{% for error in signup_form.password1.errors %}
				<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
			{% endfor %}
		</ol>
	{% endif %}
	{% if signup_form.password2.errors %}
		<ol style="color: red;">
			{% for error in signup_form.password2.errors %}
				<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
			{% endfor %}
		</ol>
	{% endif %}
	<div class="d-flex flex-row align-items-center mb-4">
		<i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
		<div class="form-outline flex-fill mb-0">
			{{ signup_form.email }}
		</div>
	</div>
	<div class="d-flex flex-row align-items-center mb-4">
		<i class="fas fa-lock fa-lg me-3 fa-fw"></i>
		<div class="form-outline flex-fill mb-0">
			{{ signup_form.password1 }}
		</div>
	</div>
	<div class="d-flex flex-row align-items-center mb-4">
		<i class="fas fa-key fa-lg me-3 fa-fw"></i>
		<div class="form-outline flex-fill mb-0">
			{{ signup_form.password2 }}
		</div>
	</div>
	<div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
		<button type="submit" class="btn btn-primary btn-lg">Зарегистрироваться</button>
	</div>
	<div style="text-align: center;">
		<h6>или</h6>
	</div>
	<div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
		<a href="{% url 'accounts:login' %}" style="color: red;">Войти</a>
	</div>
</form>

accounts/templates/accounts/include/forms/update.html
<form class="form-horizontal" action="{% url 'accounts:update_profile' %}" method="post">
	{% csrf_token %}
	{% if form.city.errors %}
		<ol style="color: red;">
			{% for error in form.email.errors %}
				<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
			{% endfor %}
		</ol>
	{% endif %}
	{% if form.language.errors %}
		<ol style="color: red;">
			{% for error in form.email.errors %}
				<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
			{% endfor %}
		</ol>
	{% endif %}
	{% if form.subscribed.errors %}
		<ol style="color: red;">
			{% for error in form.email.errors %}
				<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
			{% endfor %}
		</ol>
	{% endif %}
	{% if form.password1.errors %}
		<ol style="color: red;">
			{% for error in form.password1.errors %}
				<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
			{% endfor %}
		</ol>
	{% endif %}
	{% if form.password2.errors %}
		<ol style="color: red;">
			{% for error in form.password2.errors %}
				<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
			{% endfor %}
		</ol>
	{% endif %}
	<fieldset class="fieldset">
		<h3 class="fieldset-title">Контактные данные</h3>
		<div class="form-group">
			<label class="col-md-2  col-sm-3 col-xs-12 control-label">Город</label>
			<div class="col-md-10 col-sm-9 col-xs-12">
				{{ form.city }}
			</div>
		</div>
		<br>
		<div class="form-group">
			<label class="col-md-2  col-sm-3 col-xs-12 control-label">Язык программирования</label>
			<div class="col-md-10 col-sm-9 col-xs-12">
				{{ form.language }}
			</div>
		</div>
		<br>
		<div class="form-group">
			<label class="col-md-2  col-sm-3 col-xs-12 control-label">Статус подписки {{ form.subscribed }}</label>
		</div>
		<br>
		<div class="form-group">
			<label class="col-md-2  col-sm-3 col-xs-12 control-label">Новый пароль</label>
			<div class="col-md-10 col-sm-9 col-xs-12">
				{{ form.password1 }}
			</div>
		</div>
		<br>
		<div class="form-group">
			<label class="col-md-2  col-sm-3 col-xs-12 control-label">Повторите пароль</label>
			<div class="col-md-10 col-sm-9 col-xs-12">
				{{ form.password2 }}
			</div>
		</div>
	</fieldset>
	<hr>
	<div class="form-group">
		<div class="col-md-10 col-sm-9 col-xs-12 col-md-push-2 col-sm-push-3 col-xs-push-0">
			<input class="btn btn-primary" type="submit" value="Обновить профиль">
		</div>
	</div>
</form>