accounts/urls.py
from django.urls import path
from accounts.views import login_page, signup_page, logout_page, profile, user_update, delete_account

app_name = 'accounts'

urlpatterns = [
    path('login/', login_page, name='login'),
    path('signup/', signup_page, name='signup'),
    path('logout/', logout_page, name='logout'),
    path("profile/", profile, name='profile'),
    path("update/", user_update, name='update_profile'),
    path("delete/", delete_account, name='delete_account'),
]

main_app/urls.py
from django.urls import path
from main_app.views import main_page, vacancies, vacancy_page, help_view, company_info, create_vacancy, create_company

app_name = 'main_app'

urlpatterns = [
    path('', main_page, name='home'),
    path('vacancies/', vacancies, name='vacancies'),
    path('vacancy/<int:pk>', vacancy_page, name='vacancy'),
    path('help/', help_view, name='help'),
    path('company/info/<int:pk>', company_info, name='company_info'),
    path('vacancies/create', create_vacancy, name='create_vacancy'),
    path('companies/create', create_company, name='create_company'),
]

vacansies_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(f'admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('users/', include('accounts.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

main_app/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy


WORK_TYPE_CHOICES = [
    ("full", "Полный рабочий день"),
    ("part", "Неполный рабочий день")
]


class Company(models.Model):
    """Модель компаний"""

    name = models.CharField("Название компании", max_length=120)
    title = models.TextField("Описание компании")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Создатель",
        related_name="author_companies",
        on_delete=models.CASCADE
    )
    logo = models.ImageField(
        "Логотип",
        upload_to="company_photos/",
        null=True,
        blank=True,
        help_text="Опционально"
    )

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"Model Company: {self.name}"

    def get_absolute_url(self):
        return reverse_lazy("main_app:company_info", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компании"
        ordering = ["-pk", ]


class Cities(models.Model):
    """Модель городов"""

    name = models.CharField(
        'Название',
        max_length=220,
        unique=True
    )
    slug = models.SlugField('URL', unique=True)

    def __str__(self):
        return f'{self.name}'

    def __repr__(self):
        return f"Model Cities: {self.name}"

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Список городов'
        ordering = ['name', ]


class ProgramLanguage(models.Model):
    """Модель языков программирования"""

    name = models.CharField(
        'Название',
        max_length=220,
        unique=True
    )
    slug = models.SlugField('URL', unique=True)

    def __str__(self):
        return f'{self.name}'

    def __repr__(self):
        return f"Model ProgramLanguage: {self.name}"

    class Meta:
        verbose_name = 'Язык программирования'
        verbose_name_plural = 'Список языков программирования'
        ordering = ['name', ]


class Vacancy(models.Model):
    """Модель вакансий"""

    author = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        related_name="company_vacancies",
        verbose_name="Компания"
    )
    name = models.CharField('Название', max_length=250)
    description = models.TextField("Описание")
    city = models.ForeignKey(
        Cities,
        related_name='city_vacancies',
        verbose_name='Город',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    language = models.ForeignKey(
        ProgramLanguage,
        related_name='language_vacancies',
        verbose_name='Язык программирования',
        on_delete=models.CASCADE
    )
    phone_contact = models.CharField(
        "Номер связи",
        max_length=120
    )
    email_contact = models.CharField(
        "Email связи",
        max_length=120
    )
    billing_from = models.BigIntegerField(
        "Зарплата(от-)",
        help_text="в долларах США"
    )
    billing_to = models.BigIntegerField(
        "Зарплата(до-)",
        help_text="в долларах США"
    )
    experience = models.CharField(
        "Требуемый опыт",
        max_length=100
    )
    work_type = models.CharField(
        "Занятность",
        max_length=50,
        choices=WORK_TYPE_CHOICES,
        default=WORK_TYPE_CHOICES[0][0]
    )
    created_date = models.DateTimeField("Дата создания", auto_now_add=True)

    def __str__(self):
        return f'{self.name}'

    def __repr__(self):
        return f"Model Vacancy: {self.name}"

    def get_absolute_url(self):
        return reverse_lazy("main_app:vacancy", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Список вакансий'
        ordering = ['-created_date', ]

main_app/forms.py
from django import forms

from main_app.models import Vacancy, Company


class HelpForm(forms.Form):
    """Форма для помощи"""

    name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={"class": "input col-6", "placeholder": "Имя*"},
        ),
        label=''
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={"class": "input col-6", "placeholder": "Email*"}
        ),
        label=""
    )
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "input col-8",
                "placeholder": "Текст",
                "style": "resize: none;"
            }
        ),
        label='',
        max_length=500
    )


class VacancyForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = [
            "name", "description", "city",
            "language", "phone_contact", "email_contact",
            "billing_from", "billing_to", "experience",
            "work_type"
        ]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control"}),
            "city": forms.Select(attrs={"class": "form-select"}),
            "language": forms.Select(attrs={"class": "form-select"}),
            "phone_contact": forms.NumberInput(attrs={"class": "form-control"}),
            "email_contact": forms.TextInput(attrs={"class": "form-control"}),
            "billing_from": forms.NumberInput(attrs={"class": "form-control"}),
            "billing_to": forms.NumberInput(attrs={"class": "form-control"}),
            "experience": forms.TextInput(attrs={"class": "form-control"}),
            "work_type": forms.Select(attrs={"class": "form-select"})
        }
        label = {
            "name": "Название",
            "description": "Описание",
            "city": "Город",
            "language": "Язык программирования",
            "phone_contact": "Контактный номер",
            "email_contact": "Контактный email",
            "billing_from": "Зарплата(от-) $",
            "billing_to": "Зарплата(до-) $",
            "experience": "Опыт работы",
            "work_type": "Формат работы",
        }


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ["name", "title", "logo"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "title": forms.Textarea(attrs={"class": "form-control"}),
            "logo": forms.FileInput(attrs={"class": "form-control"})
        }

main_app/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from loguru import logger

from main_app.email_senders import help_sender
from main_app.forms import HelpForm, VacancyForm, CompanyForm
from main_app.models import Vacancy, ProgramLanguage, Cities, Company
# from main_app.tasks import help_send


def main_page(request: WSGIRequest):
    """Главная страница"""

    last_created_vacancies = Vacancy.objects.all()[:6]
    help_form = HelpForm()
    context = {
        "title": "Home",
        "last_created": last_created_vacancies,
        "help_form": help_form
    }
    return render(
        request,
        "main_app/index.html",
        context=context
    )


@login_required(login_url="accounts:login")
def help_view(request: WSGIRequest):
    """Обработчик формы помощи"""

    if not request.method == "POST":
        messages.info(request, "Разрешен только POST метод")
        return redirect("main_app:home")
    help_form = HelpForm(request.POST)
    if help_form.is_valid():
        name = help_form.cleaned_data["name"]
        email = help_form.cleaned_data["email"]
        text = help_form.cleaned_data["text"]
        # help_send.delay(name, email, text)
        if help_sender(name, email, text):
            messages.success(request, "Заявка отправлена успешно!")
        else:
            messages.error(request, "Не удалось отправить! Попробуйте позже!")
    else:
        for errors in help_form.errors:
            for error in errors:
                messages.error(request, error)
    return redirect("main_app:vacancies")


@login_required(login_url='accounts:login')
def vacancies(request: WSGIRequest):
    """Страница для вакансий"""

    help_form = HelpForm()
    cities = Cities.objects.all()
    langs = ProgramLanguage.objects.all()
    get_city = request.GET.get("city")
    get_lang = request.GET.get("lang")
    filters = {}
    if get_city or get_lang:
        if get_city:
            check_city = Cities.objects.filter(slug=get_city).first()
            if check_city:
                filters["city"] = check_city
        if get_lang:
            check_lang = ProgramLanguage.objects.filter(slug=get_lang).first()
            if check_lang:
                filters["language"] = check_lang
    if filters:
        vacancies_list = Vacancy.objects.prefetch_related("city", "language").filter(**filters).all()
    else:
        vacancies_list = Vacancy.objects.prefetch_related("city", "language").all()
    page = request.GET.get("page", 1)
    try:
        new_page = int(page)
    except ValueError:
        logger.add(settings.BASE_DIR / 'logs/all/all.log', level="INFO")
        logger.warning("value error(str) with pagination page number")
        new_page = 1
    paginator = Paginator(vacancies_list, settings.PAGINATION_CONTENT_LENGTH)
    get_obj = paginator.get_page(int(new_page))
    context = {
        "title": "Вакансии",
        'vacancies': get_obj,
        "cities": cities,
        "langs": langs,
        "filter_city": get_city,
        "filter_lang": get_lang,
        "help_form": help_form
    }
    return render(
        request,
        "main_app/vacancies.html",
        context=context
    )


@login_required(login_url='accounts:login')
def vacancy_page(request: WSGIRequest, pk: int):
    vacancy = get_object_or_404(Vacancy, pk=pk)
    help_form = HelpForm()
    context = {
        "title": vacancy.name,
        "vacancy": vacancy,
        "help_form": help_form
    }
    return render(
        request,
        "main_app/vacancy_page.html",
        context=context
    )


@login_required(login_url='accounts:login')
def company_info(request: WSGIRequest, pk):
    company = get_object_or_404(Company, pk=pk)
    help_form = HelpForm()
    context = {
        "title": company.name,
        "company": company,
        "help_form": help_form
    }
    return render(
        request,
        "main_app/company_info.html",
        context=context
    )


@login_required(login_url="accounts:login")
def create_vacancy(request: WSGIRequest):
    if not request.user.author_companies.first():
        messages.info(request, "Сначала создайте компанию")
        return redirect("main_app:create_company")
    if request.method == "POST":
        create_form = VacancyForm(request.POST)
        if create_form.is_valid():
            save = create_form.save(commit=False)
            save.author = request.user.author_companies.first()
            save.save()
            messages.success(request, "Успешно добавлено!")
            return redirect("main_app:home")
    else:
        create_form = VacancyForm()
    help_form = HelpForm()
    context = {
        "title": "Добавить вакансию",
        "help_form": help_form,
        "create_form": create_form
    }
    return render(
        request,
        "main_app/create_vacancy.html",
        context=context
    )


@login_required(login_url="accounts:login")
def create_company(request: WSGIRequest):
    if request.user.author_companies.first():
        messages.info(request, "У вас уже есть компания!")
        return redirect("main_app:home")
    if request.method == "POST":
        create_form = CompanyForm(request.POST, request.FILES)
        if create_form.is_valid():
            save = create_form.save(commit=False)
            save.owner = request.user
            save.save()
            messages.success(request, "Успешно добавлено!")
            return redirect("main_app:home")
    else:
        create_form = CompanyForm()
    help_form = HelpForm()
    context = {
        "title": "Добавить вакансию",
        "help_form": help_form,
        "create_form": create_form
    }
    return render(
        request,
        "main_app/create_company.html",
        context=context
    )

main_app/templates/main_app/include/all_vacancies.html
<div class="row col-lg-12 col-sm-12 col-md-12 col-12" style="padding: 10px; margin-left: 5px;">
	{% for vacancy in vacancies %}
		<div class="vacancy-item" style="padding: 5px;">
			<div class="col-md-12">
				<div class="card border-warning">
					<h5 class="card-header border-warning fw-bold" style="background: #f41b1be6">{{ vacancy.name }}</h5>
					<div class="card-body">
						<p class="card-text">{{ vacancy.description|truncatechars:200 }}</p>
						{% if vacancy.city %}
							<small>Город(страна): {{ vacancy.city }} | {{ vacancy.created_date|date:"d.m.Y" }}г.</small>
						{% else %}
							<small>Город(страна): нет | {{ vacancy.created_date|date:"d.m.Y" }}г.</small>
						{% endif %}
						<br>
						<small class="card-text">Язык: {{ vacancy.language }} | Компания: {{ vacancy.author }}</small>
						<br>
						<a href="{{ vacancy.get_absolute_url }}" class="btn btn-success">К вакансии</a>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}
	<div class="pagination centered" style="padding: 5px; display: flex; align-items: center; justify-content: center ">
		{% if vacancies.has_previous %}
			<button class="btn" style="background: black; color: white; margin-right: 20px;">
				<a href="?page={{vacancies.previous_page_number}}&{{ filter_city }}&{{ filter_lang }}"
				   style="background: black; color: white;">Предыдущая
					страница
				</a>
			</button>
			<br><br>
		{% endif %}
		{% if vacancies.has_next %}
			<button class="btn" style="background: black; color: white; margin-left: 20px; float: right;">
				<a href="?page={{vacancies.next_page_number}}{% if filter_city %}&city={{ filter_city }}{% endif %}{% if filter_lang %}&lang={{ filter_lang }}{% endif %}"
				   style="background: black; color: white; ">Следующая
					страница
				</a>
			</button>
			<br>
		{% endif %}
	</div>
</div>

main_app/templates/main_app/include/company_info.html
<div class="container">
    <h1>{{ company.name.capitalize }}</h1>
    <div class="img-container">
        {% if company.logo %}
            <img class="rounded float-left col-xxl-4 col-xl-4 col-md-6 col-lg-6 col-sm-8 col-12"
             style="width: 500px; height: 250px;" src="{{ company.logo.url }}" alt="company logo">
        {% endif %}
    </div>
    <br><br>
    <h4>Описание</h4>
    <div class="card mb-4">
        <div class="card-body">
            <p class="card-text">
                {{ company.title.capitalize }}
            </p>
        </div>
    </div>
</div>

main_app/templates/main_app/include/last_created_vacancies.html
<article class="row">
	{% for vacancy in last_created %}
		<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6 vacancy-item" style="padding: 15px; height: 100%;">
			<div class="card border-warning">
				<h5 class="card-header border-warning fw-bold" style="background: #f41b1be6">{{ vacancy.name }}</h5>
				<div class="card-body">
					<p class="card-text">{{ vacancy.description|truncatechars:200 }}</p>
					{% if vacancy.city %}
						<small>Город(страна): {{ vacancy.city }} | {{ vacancy.created_date|date:"d.m.Y" }}г.</small>
					{% else %}
						<small>Город(страна): нет | {{ vacancy.created_date|date:"d.m.Y" }}г.</small>
					{% endif %}
					<br>
					<small class="card-text">Язык: {{ vacancy.language }} | Компания: {{ vacancy.author }}</small>
					<br><br>
					<a href="{{ vacancy.get_absolute_url }}" class="btn btn-success">К вакансии</a>
				</div>
			</div>
		</div>
	{% endfor %}
</article>

main_app/templates/main_app/include/vacancy_card.html
<div class="container">
    <h1>{{ vacancy.name.capitalize }}</h1>
    <div class="billing">
        <h4>Зарплата</h4>
        <p class="mb-0">от: {{ vacancy.billing_from }}$  до: {{ vacancy.billing_to }}$</p>
    </div>
    <br>
    <div class="company mb-4">
        <div class="row">
            <h4 class="col-xxl-4 col-xl-4 col-md-6 col-lg-6 col-sm-8 col-12">{{ vacancy.author.name.capitalize }}</h4>
            {% if vacancy.author.logo %}
                <img class="rounded float-left col-xxl-4 col-xl-4 col-md-6 col-lg-6 col-sm-8 col-12" style="width: 100px; height: 50px;" src="{{ vacancy.author.logo.url }}" alt="company logo">
            {% endif %}
        </div>
        <a class="btn btn-primary" href="{{ vacancy.author.get_absolute_url }}">Информация о компании</a>
    </div>
    <h4>Основная информация</h4>
    <p class="mb-0">Город: {{ vacancy.city.name.capitalize }}</p>
    <p class="mb-0">Язык программирования: {{ vacancy.language.name.capitalize }}</p>
    <p class="mb-0">Требуемый опыт: {{ vacancy.experience.capitalize }}</p>
    <p class="mb-0">Занятность: {{ vacancy.get_work_type_display.capitalize }}</p>
    <p class="mb-4">Дата создания: {{ vacancy.created_date }}</p>
    <h4>Описание</h4>
    <div class="card mb-4">
        <div class="card-body">
            <p class="card-text">
                {{ vacancy.description.capitalize }}
            </p>
        </div>
    </div>
    <h4>Контакты</h4>
    <p class="mb-0">email: {{ vacancy.email_contact }}</p>
    <p class="mb-4">Номер телефона: {{ vacancy.phone_contact }}</p>
</div>