accounts/urls.py
from django.urls import path
from accounts.views import login_page, signup_page, logout_page, profile, user_update, delete_account

app_name = 'accounts'

urlpatterns = [
    path('login/', login_page, name='login'),
    path('signup/', signup_page, name='signup'),
    path('logout/', logout_page, name='logout'),
    path("profile/", profile, name='profile'),
    path("update/", user_update, name='update_profile'),
    path("delete/", delete_account, name='delete_account'),
]

main_app/urls.py
from django.urls import path
from main_app.views import main_page, vacancies, vacancy_page, help_view, company_info, create_vacancy, create_company

app_name = 'main_app'

urlpatterns = [
    path('', main_page, name='home'),
    path('vacancies/', vacancies, name='vacancies'),
    path('vacancy/<int:pk>', vacancy_page, name='vacancy'),
    path('help/', help_view, name='help'),
    path('company/info/<int:pk>', company_info, name='company_info'),
    path('vacancies/create', create_vacancy, name='create_vacancy'),
    path('companies/create', create_company, name='create_company'),
]

vacansies_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(f'admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('users/', include('accounts.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

main_app/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy


WORK_TYPE_CHOICES = [
    ("full", "Полный рабочий день"),
    ("part", "Неполный рабочий день")
]


class Company(models.Model):
    """Модель компаний"""

    name = models.CharField("Название компании", max_length=120)
    title = models.TextField("Описание компании")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Создатель",
        related_name="author_companies",
        on_delete=models.CASCADE
    )
    logo = models.ImageField(
        "Логотип",
        upload_to="company_photos/",
        null=True,
        blank=True,
        help_text="Опционально"
    )

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"Model Company: {self.name}"

    def get_absolute_url(self):
        return reverse_lazy("main_app:company_info", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компании"
        ordering = ["-pk", ]


class Cities(models.Model):
    """Модель городов"""

    name = models.CharField(
        'Название',
        max_length=220,
        unique=True
    )
    slug = models.SlugField('URL', unique=True)

    def __str__(self):
        return f'{self.name}'

    def __repr__(self):
        return f"Model Cities: {self.name}"

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Список городов'
        ordering = ['name', ]


class ProgramLanguage(models.Model):
    """Модель языков программирования"""

    name = models.CharField(
        'Название',
        max_length=220,
        unique=True
    )
    slug = models.SlugField('URL', unique=True)

    def __str__(self):
        return f'{self.name}'

    def __repr__(self):
        return f"Model ProgramLanguage: {self.name}"

    class Meta:
        verbose_name = 'Язык программирования'
        verbose_name_plural = 'Список языков программирования'
        ordering = ['name', ]


class Vacancy(models.Model):
    """Модель вакансий"""

    author = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        related_name="company_vacancies",
        verbose_name="Компания"
    )
    name = models.CharField('Название', max_length=250)
    description = models.TextField("Описание")
    city = models.ForeignKey(
        Cities,
        related_name='city_vacancies',
        verbose_name='Город',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    language = models.ForeignKey(
        ProgramLanguage,
        related_name='language_vacancies',
        verbose_name='Язык программирования',
        on_delete=models.CASCADE
    )
    phone_contact = models.CharField(
        "Номер связи",
        max_length=120
    )
    email_contact = models.CharField(
        "Email связи",
        max_length=120
    )
    billing_from = models.BigIntegerField(
        "Зарплата(от-)",
        help_text="в долларах США"
    )
    billing_to = models.BigIntegerField(
        "Зарплата(до-)",
        help_text="в долларах США"
    )
    experience = models.CharField(
        "Требуемый опыт",
        max_length=100
    )
    work_type = models.CharField(
        "Занятность",
        max_length=50,
        choices=WORK_TYPE_CHOICES,
        default=WORK_TYPE_CHOICES[0][0]
    )
    created_date = models.DateTimeField("Дата создания", auto_now_add=True)

    def __str__(self):
        return f'{self.name}'

    def __repr__(self):
        return f"Model Vacancy: {self.name}"

    def get_absolute_url(self):
        return reverse_lazy("main_app:vacancy", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Список вакансий'
        ordering = ['-created_date', ]

main_app/forms.py
from django import forms

from main_app.models import Vacancy, Company


class HelpForm(forms.Form):
    """Форма для помощи"""

    name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={"class": "input col-6", "placeholder": "Имя*"},
        ),
        label=''
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={"class": "input col-6", "placeholder": "Email*"}
        ),
        label=""
    )
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "input col-8",
                "placeholder": "Текст",
                "style": "resize: none;"
            }
        ),
        label='',
        max_length=500
    )


class VacancyForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = [
            "name", "description", "city",
            "language", "phone_contact", "email_contact",
            "billing_from", "billing_to", "experience",
            "work_type"
        ]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control"}),
            "city": forms.Select(attrs={"class": "form-select"}),
            "language": forms.Select(attrs={"class": "form-select"}),
            "phone_contact": forms.NumberInput(attrs={"class": "form-control"}),
            "email_contact": forms.TextInput(attrs={"class": "form-control"}),
            "billing_from": forms.NumberInput(attrs={"class": "form-control"}),
            "billing_to": forms.NumberInput(attrs={"class": "form-control"}),
            "experience": forms.TextInput(attrs={"class": "form-control"}),
            "work_type": forms.Select(attrs={"class": "form-select"})
        }
        label = {
            "name": "Название",
            "description": "Описание",
            "city": "Город",
            "language": "Язык программирования",
            "phone_contact": "Контактный номер",
            "email_contact": "Контактный email",
            "billing_from": "Зарплата(от-) $",
            "billing_to": "Зарплата(до-) $",
            "experience": "Опыт работы",
            "work_type": "Формат работы",
        }


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ["name", "title", "logo"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "title": forms.Textarea(attrs={"class": "form-control"}),
            "logo": forms.FileInput(attrs={"class": "form-control"})
        }

main_app/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from loguru import logger

from main_app.email_senders import help_sender
from main_app.forms import HelpForm, VacancyForm, CompanyForm
from main_app.models import Vacancy, ProgramLanguage, Cities, Company
# from main_app.tasks import help_send


def main_page(request: WSGIRequest):
    """Главная страница"""

    last_created_vacancies = Vacancy.objects.all()[:6]
    help_form = HelpForm()
    context = {
        "title": "Home",
        "last_created": last_created_vacancies,
        "help_form": help_form
    }
    return render(
        request,
        "main_app/index.html",
        context=context
    )


@login_required(login_url="accounts:login")
def help_view(request: WSGIRequest):
    """Обработчик формы помощи"""

    if not request.method == "POST":
        messages.info(request, "Разрешен только POST метод")
        return redirect("main_app:home")
    help_form = HelpForm(request.POST)
    if help_form.is_valid():
        name = help_form.cleaned_data["name"]
        email = help_form.cleaned_data["email"]
        text = help_form.cleaned_data["text"]
        # help_send.delay(name, email, text)
        if help_sender(name, email, text):
            messages.success(request, "Заявка отправлена успешно!")
        else:
            messages.error(request, "Не удалось отправить! Попробуйте позже!")
    else:
        for errors in help_form.errors:
            for error in errors:
                messages.error(request, error)
    return redirect("main_app:vacancies")


@login_required(login_url='accounts:login')
def vacancies(request: WSGIRequest):
    """Страница для вакансий"""

    help_form = HelpForm()
    cities = Cities.objects.all()
    langs = ProgramLanguage.objects.all()
    get_city = request.GET.get("city")
    get_lang = request.GET.get("lang")
    filters = {}
    if get_city or get_lang:
        if get_city:
            check_city = Cities.objects.filter(slug=get_city).first()
            if check_city:
                filters["city"] = check_city
        if get_lang:
            check_lang = ProgramLanguage.objects.filter(slug=get_lang).first()
            if check_lang:
                filters["language"] = check_lang
    if filters:
        vacancies_list = Vacancy.objects.prefetch_related("city", "language").filter(**filters).all()
    else:
        vacancies_list = Vacancy.objects.prefetch_related("city", "language").all()
    page = request.GET.get("page", 1)
    try:
        new_page = int(page)
    except ValueError:
        logger.add(settings.BASE_DIR / 'logs/all/all.log', level="INFO")
        logger.warning("value error(str) with pagination page number")
        new_page = 1
    paginator = Paginator(vacancies_list, settings.PAGINATION_CONTENT_LENGTH)
    get_obj = paginator.get_page(int(new_page))
    context = {
        "title": "Вакансии",
        'vacancies': get_obj,
        "cities": cities,
        "langs": langs,
        "filter_city": get_city,
        "filter_lang": get_lang,
        "help_form": help_form
    }
    return render(
        request,
        "main_app/vacancies.html",
        context=context
    )


@login_required(login_url='accounts:login')
def vacancy_page(request: WSGIRequest, pk: int):
    vacancy = get_object_or_404(Vacancy, pk=pk)
    help_form = HelpForm()
    context = {
        "title": vacancy.name,
        "vacancy": vacancy,
        "help_form": help_form
    }
    return render(
        request,
        "main_app/vacancy_page.html",
        context=context
    )


@login_required(login_url='accounts:login')
def company_info(request: WSGIRequest, pk):
    company = get_object_or_404(Company, pk=pk)
    help_form = HelpForm()
    context = {
        "title": company.name,
        "company": company,
        "help_form": help_form
    }
    return render(
        request,
        "main_app/company_info.html",
        context=context
    )


@login_required(login_url="accounts:login")
def create_vacancy(request: WSGIRequest):
    if not request.user.author_companies.first():
        messages.info(request, "Сначала создайте компанию")
        return redirect("main_app:create_company")
    if request.method == "POST":
        create_form = VacancyForm(request.POST)
        if create_form.is_valid():
            save = create_form.save(commit=False)
            save.author = request.user.author_companies.first()
            save.save()
            messages.success(request, "Успешно добавлено!")
            return redirect("main_app:home")
    else:
        create_form = VacancyForm()
    help_form = HelpForm()
    context = {
        "title": "Добавить вакансию",
        "help_form": help_form,
        "create_form": create_form
    }
    return render(
        request,
        "main_app/create_vacancy.html",
        context=context
    )


@login_required(login_url="accounts:login")
def create_company(request: WSGIRequest):
    if request.user.author_companies.first():
        messages.info(request, "У вас уже есть компания!")
        return redirect("main_app:home")
    if request.method == "POST":
        create_form = CompanyForm(request.POST, request.FILES)
        if create_form.is_valid():
            save = create_form.save(commit=False)
            save.owner = request.user
            save.save()
            messages.success(request, "Успешно добавлено!")
            return redirect("main_app:home")
    else:
        create_form = CompanyForm()
    help_form = HelpForm()
    context = {
        "title": "Добавить вакансию",
        "help_form": help_form,
        "create_form": create_form
    }
    return render(
        request,
        "main_app/create_company.html",
        context=context
    )

main_app/templates/main_app/include/forms/add_company.html
<div style="border-radius: 10px;">
	<form method="post" class="text-center" enctype="multipart/form-data"
		  style="padding: 20px; border-radius: 10px;">
		<h4>Добавьте Компанию</h4>
		{% csrf_token %}
		{% if create_form.name.errors %}
			<ol style="color: red;">
				{% for error in create_form.name.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
		{% if create_form.title.errors %}
			<ol style="color: red;">
				{% for error in create_form.title.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
		{% if create_form.logo.errors %}
			<ol style="color: red;">
				{% for error in create_form.logo.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
		<div class="col-6 mx-auto mt-5">
			<div class="row justify-content-center">
				<div class="form-outline mb-2 col-7" style="border-radius: 5px;">
					{{ create_form.name.label }}
					{{ create_form.name }}
				</div>
				<div class="form-outline mb-2 col-7">
					{{ create_form.title.label }}
					{{ create_form.title }}
				</div>
				<div class="form-outline mb-2 col-7">
					{{ create_form.logo.label }}
					{{ create_form.logo }}
				</div>
			</div>
		</div>
		<br>
		<button type="submit" class="btn btn-danger btn-block mb-2">Создать</button>
	</form>
</div>

main_app/templates/main_app/include/forms/add_vacancy.html
<div style="border-radius: 10px;">
	<form method="post" class="text-center"
		  style="padding: 20px; border-radius: 10px;">
		<h4>Добавьте вакансию</h4>
		{% csrf_token %}
		{% if create_form.name.errors %}
			<ol style="color: red;">
				{% for error in create_form.name.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
		{% if create_form.description.errors %}
			<ol style="color: red;">
				{% for error in create_form.description.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
		{% if create_form.city.errors %}
			<ol style="color: red;">
				{% for error in create_form.city.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
        {% if create_form.language.errors %}
			<ol style="color: red;">
				{% for error in create_form.language.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
        {% if create_form.phone_contact.errors %}
			<ol style="color: red;">
				{% for error in create_form.phone_contact.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
        {% if create_form.email_contact.errors %}
			<ol style="color: red;">
				{% for error in email_contact.city.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
        {% if create_form.billing_from.errors %}
			<ol style="color: red;">
				{% for error in create_form.billing_from.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
        {% if create_form.billing_to.errors %}
			<ol style="color: red;">
				{% for error in create_form.billing_to.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
        {% if create_form.experience.errors %}
			<ol style="color: red;">
				{% for error in create_form.experience.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
        {% if create_form.work_type.errors %}
			<ol style="color: red;">
				{% for error in create_form.work_type.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
		<div class="col-6 mx-auto mt-5">
			<div class="row">
				<div class="form-outline mb-2 col-4" style="border-radius: 5px;">
					{{ create_form.name.label }}
					{{ create_form.name }}
				</div>
				<div class="form-outline mb-2 col-4">
					{{ create_form.phone_contact.label }}
					{{ create_form.phone_contact }}
				</div>
				<div class="form-outline mb-2 col-4">
					{{ create_form.email_contact.label }}
					{{ create_form.email_contact }}
				</div>
				<div class="form-outline mb-2 col-4">
					{{ create_form.billing_from.label }}(в долларах США)
					{{ create_form.billing_from }}
				</div>
				<div class="form-outline mb-2 col-4">
					{{ create_form.billing_to.label }}(в долларах США)
					{{ create_form.billing_to }}
				</div>
				<div class="form-outline mb-2 col-4">
					{{ create_form.experience.label }}
					{{ create_form.experience }}
				</div>
				<div class="col-12">
					<div class="row">
						<div class="form-outline mb-2 col-4">
							{{ create_form.city.label }}
							{{ create_form.city }}
						</div>
						<div class="form-outline mb-2 col-4">
							{{ create_form.language.label }}
							{{ create_form.language }}
						</div>
						<div class="form-outline mb-2 col-4">
							{{ create_form.work_type.label }}
							{{ create_form.work_type }}
						</div>
					</div>
				</div>
				<div class="form-outline mb-2 col-12">
					{{ create_form.description.label }}
					{{ create_form.description }}
				</div>
			</div>
		</div>
		<button type="submit" class="btn btn-primary btn-block mb-2">Отправить</button>
	</form>
</div>

main_app/templates/main_app/include/forms/help.html
<div style="border-radius: 10px;" class="mb-4">
	<form method="post" action="{% url 'main_app:help' %}"
		  style="text-align: center; background: linear-gradient(rgba(155, 89, 182, 0.6), rgba(200, 30, 0, 0.6)); padding: 20px; border-radius: 10px;">
		<h4>Остались вопросы? Пишите нам!</h4>
		{% csrf_token %}
		{% if help_form.name.errors %}
			<ol style="color: red;">
				{% for error in help_form.name.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
		{% if help_form.email.errors %}
			<ol style="color: red;">
				{% for error in help_form.email.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
		{% if help_form.text.errors %}
			<ol style="color: red;">
				{% for error in help_form.text.errors %}
					<li style="list-style-type: none;"><strong>{{ error|escape }}</strong></li>
				{% endfor %}
			</ol>
		{% endif %}
		<!-- Name input -->
		<div class="form-outline mb-2" style="border-radius: 5px;">
			{{ help_form.name }}
		</div>

		<!-- Email input -->
		<div class="form-outline mb-2">
			{{ help_form.email }}
		</div>

		<!-- Message input -->
		<div class="form-outline mb-2">
			{{ help_form.text }}
		</div>
		<button type="submit" class="btn btn-warning btn-block mb-2">Отправить</button>
	</form>
</div>